### ISSUE TITLE
Game Summary - Features

### ISSUE THREAD

**Issue by apaleshi** [robpurvessmith/SlowJams#20]
Here's a visual summary of the priorities / features of the game summary interface.

[Game Summary - User Interface.pdf](https://github.com/robpurvessmith/SlowJams/files/160605/Game.Summary.-.User.Interface.pdf)

**Comment by apaleshi** [comment]
Definition of "Contribution 2"
[Explanation of Contribution.pdf](https://github.com/robpurvessmith/SlowJams/files/160618/Explanation.of.Contribution.pdf)

**Comment by BrandonNoad** [comment]
- [x] Change Game col value to Away Team @ Home Team
- [x] Add date col
- [x] Filter only on Bout/Date cols
- [x] Add Contribution #2 col
- [x] Total/Avg rows
